# Generated by Django 2.2.6 on 2019-10-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del curso', max_length=50, verbose_name='nombre del curso')),
                ('tipo', models.CharField(help_text='ejemplo: computación', max_length=50)),
                ('cantidad_horas', models.PositiveSmallIntegerField(verbose_name='cantidad de horas')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.PositiveSmallIntegerField(help_text='Ingrese el dni del alumno', unique=True)),
                ('apellido', models.CharField(help_text='Ingrese el apellido del alumno', max_length=50)),
                ('nombre', models.CharField(help_text='Ingrese el nombre del alumno', max_length=50)),
                ('observación', models.TextField(blank=True, null=True)),
                ('curso', models.ManyToManyField(to='aplicacion.Curso')),
            ],
        ),
    ]
